version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: db_postgres
    environment:
      POSTGRES_USER: federico
      POSTGRES_PASSWORD: federicocrack
      POSTGRES_DB: puma_db
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: