export enum Category{
    MATEMATICAS = "MATEMATICAS",
    PROBABILIDAD_ESTADISTICA_Y_OPTIMIZACION = "PROBABILIDAD_ESTADISTICA_Y_OPTIMIZACION",
    MATEMATICAS_COMPUTACIONALES = "MATEMATICAS_COMPUTACIONALES",
    COMPUTACION = "COMPUTACION",
    HUMANISTICA_SOCIAL = "HUMANISTICA_SOCIAL",
    MODELADO_ANALITICO = "MODELADO_ANALITICO",
    MODELADO_ESTOCASTICO = "MODELADO_ESTOCASTICO",
    ADMINISTRACION_Y_FINANZAS = "ADMINISTRACION_Y_FINANZAS",
    SISTEMAS_COMPUTACIONALES = "SISTEMAS_COMPUTACIONALES",
    CIENCIAS_DE_LA_COMPUTACION = "CIENCIAS_DE_LA_COMPUTACION"   
}