### POST 
POST http://localhost:3001/api/students
Content-Type: application/json

{
  "accountNumber": 321191300,
  "name": "JOAQUIN RACIEL",
  "lastNameP": "RESENDIZ",
  "lastNameM": "RODRIGUEZ",
  "interest": "GÜERAS",
  "currentSemester": 6,
  "average": 9.2,
  "email": "32@pcpuma.acatlan.com",
  "password": "12345678"
}
###
POST http://localhost:3001/api/autenticacion/login
Content-Type: application/json

{
  "accountNumber": 321191300,
  "password": "12345678"
}

### GET 
GET http://localhost:3001/api/students/32@pcpuma.acatlan.com

###
GET http://localhost:3001/api/students/account/321191300