### POST 
POST http://localhost:3001/api/students
Content-Type: application/json

{
  "accountNumber": 100000,
  "name": "JOSE EMMANUEL",
  "lastNameP": "ISLAS",
  "lastNameM": "ROMERO",
  "interest": "MONICA",
  "currentSemester": 6,
  "average": 9.0,
  "email": "30@pcpuma.acatlan.com",
  "password": "12345678",
  "addressId" : "cebcc6ce-4c58-406a-991b-2b45e1c84188"
}
###
POST http://localhost:3001/api/autenticacion/login
Content-Type: application/json

{
  "accountNumber": 100003,
  "password": "12345678"
}

### GET 
GET http://localhost:3001/api/students/32@pcpuma.acatlan.com

###
GET http://localhost:3001/api/students/account/321191300