POST http://localhost:3001/api/contests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkMmVlODZmMi04MTc0LTRmNTctYTliOS1kYjZjNzBkYjgzNDIiLCJuYW1lIjoiTFVJUyBHSUxCRVJUTyIsImFjY291bnROdW1iZXIiOjEwMDAwMywiaWF0IjoxNzc4OTE5ODc0LCJleHAiOjE3Nzg5MjcwNzR9.TFobvUMz13-7jX9Lj47eiBUV7qtYMnsjpNKMMHStMe4
Content-Type: application/json

{
    "name":"Hackaton NESTJS",
    "categoryId": "e9dcfa15-0f22-455d-828d-d43c28c10489"
}
###
POST http://localhost:3001/api/contests/enroll
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkMmVlODZmMi04MTc0LTRmNTctYTliOS1kYjZjNzBkYjgzNDIiLCJuYW1lIjoiTFVJUyBHSUxCRVJUTyIsImFjY291bnROdW1iZXIiOjEwMDAwMywiaWF0IjoxNzc4OTE5ODc0LCJleHAiOjE3Nzg5MjcwNzR9.TFobvUMz13-7jX9Lj47eiBUV7qtYMnsjpNKMMHStMe4
Content-Type: application/json

{
    "studentId":"d2ee86f2-8174-4f57-a9b9-db6c70db8342",
    "contestId":"f44965e8-35a2-46df-99f0-cb6c78e58d49"
}


