export enum KnowledgeArea {
    CIENCIAS_FISICO_MATEMATICAS_Y_DE_LAS_INGENIERIAS = "CIENCIAS_FISICO_MATEMATICAS_Y_DE_LAS_INGENIERIAS",
    CIENCIAS_BIOLOGICAS_Y_DE_LA_SALUD = "CIENCIAS_BIOLOGICAS_Y_DE_LA_SALUD",
    CIENCIAS_SOCIALES = "CIENCIAS_SOCIALES",
    HUMANIDADES_Y_ARTES = "HUMANIDADES_Y_ARTES",
}